version: '3'

vars:
  PROJECT_NAME: thinking-trace-viewer

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - npm install

  dev:
    desc: Start development server
    cmds:
      - npm run dev

  build:
    desc: Build standalone viewer
    cmds:
      - npm run build

  build:lib:
    desc: Build as embeddable library
    cmds:
      - npm run build:lib

  preview:
    desc: Preview production build
    cmds:
      - npm run preview

  test:
    desc: Run tests in watch mode
    cmds:
      - npm run test

  test:run:
    desc: Run tests once
    cmds:
      - npm run test:run

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - npm run test:coverage

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - npm run typecheck

  lint:
    desc: Run ESLint
    cmds:
      - npm run lint

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist node_modules/.vite

  clean:all:
    desc: Clean everything including node_modules
    cmds:
      - rm -rf dist node_modules

  check:
    desc: Run all checks (typecheck + test)
    cmds:
      - task: typecheck
      - task: test:run

  ci:
    desc: Run CI pipeline
    cmds:
      - task: install
      - task: typecheck
      - task: test:run
      - task: build
